# Generated by Django 3.2.8 on 2021-10-25 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Track',
            new_name='PlaylistTrack',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='tracks',
        ),
    ]
