# Generated by Django 3.2.8 on 2021-10-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211025_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlisttracks',
            field=models.ManyToManyField(to='main_app.PlaylistTrack'),
        ),
    ]
