# Generated by Django 3.2.8 on 2021-10-25 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_playlist_playlisttracks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='playlisttracks',
        ),
        migrations.AddField(
            model_name='playlisttrack',
            name='playlist',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main_app.playlist'),
            preserve_default=False,
        ),
    ]
