# Generated by Django 3.2.8 on 2021-10-25 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20211025_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlisttrack',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.playlist', unique=True),
        ),
    ]
